"use client";

import { useState } from "react";
import { AdminDataTable, AdminDialog, AdminSection, AdminStatusBadge } from "@/components/admin-primitives";
import type { useClassAdmin } from "@/components/class-admin-hooks";
import type { ReplayPlaylist } from "@/lib/schedule-replay-api";

export function AdminReplayPlaylists({ store }: { store: ReturnType<typeof useClassAdmin> }) {
  const [draft, setDraft] = useState<ReplayPlaylist | null>(null);
  const [deleting, setDeleting] = useState<ReplayPlaylist | null>(null);
  return <AdminSection title="Playlist"><button className="button button-primary" type="button" disabled={store.loading} onClick={() => setDraft({ id: 0, program_id: 0, title: "", description: "", status: "draft", sort_order: 0 })}>Tambah Playlist</button><AdminDataTable caption="Playlist Replay" rows={store.playlists} rowKey={item => String(item.id)} columns={[{ key: "title", header: "Judul", cell: item => item.title }, { key: "program", header: "Program", cell: item => store.programs.find(program => program.id === item.program_id)?.name || "—" }, { key: "status", header: "Status", cell: item => <AdminStatusBadge status={item.status === "published" ? "Published" : "Draft"} /> }]} actions={{ cell: item => <div className="admin-page-actions"><button className="button" type="button" onClick={() => setDraft({ ...item })}>Edit</button><button className="button" type="button" onClick={() => setDeleting(item)}>Hapus</button></div> }} /><AdminDialog open={!!draft} title="Playlist Replay" close={() => setDraft(null)}>{draft && <form className="admin-prototype-form" onSubmit={async event => { event.preventDefault(); if (await store.write(draft, "save", true)) setDraft(null); }}><label className="admin-field">Judul<input required value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} /></label><label className="admin-field">Program<select required value={draft.program_id || ""} onChange={event => setDraft({ ...draft, program_id: Number(event.target.value) })}><option value="">Pilih program</option>{store.programs.filter(item => /^n[1-5]$/.test(item.code)).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="admin-field">Deskripsi<textarea value={draft.description || ""} onChange={event => setDraft({ ...draft, description: event.target.value })} /></label><label className="admin-field">Urutan<input required min="0" step="1" type="number" value={draft.sort_order} onChange={event => setDraft({ ...draft, sort_order: Number(event.target.value) })} /></label><label className="admin-field">Status<select value={draft.status} onChange={event => setDraft({ ...draft, status: event.target.value })}><option value="draft">Draft</option><option value="published">Published</option></select></label>{store.mutationError && <p role="alert">{store.mutationError}</p>}<button disabled={store.busy} className="button button-primary" type="submit">Simpan</button></form>}</AdminDialog><AdminDialog open={!!deleting} title="Hapus Playlist?" close={() => setDeleting(null)} actions={<button className="button button-primary" disabled={store.busy} onClick={async () => { if (deleting && await store.write(deleting, "delete", true)) setDeleting(null); }}>Hapus</button>}><p>Hapus {deleting?.title}? Video dalam playlist ikut dihapus.</p>{store.mutationError && <p role="alert">{store.mutationError}</p>}</AdminDialog></AdminSection>;
}
